import React from 'react';
import CrudPage from '../components/CrudPage';

export default function ReportsPage() {
  return (
    <CrudPage
      resource="reports"
      title="Patient Reports"
      icon="📈"
      columns={[
        { key: 'id', label: 'ID' },
        { key: 'first_name', label: 'Patient', render: (_, row) => `${row.first_name} ${row.last_name}` },
        { key: 'report_type', label: 'Type' },
        { key: 'title', label: 'Title' },
        { key: 'generated_by', label: 'Generated By' },
        { key: 'status', label: 'Status', badge: true },
        { key: 'created_at', label: 'Created', datetime: true },
      ]}
      formFields={[
        { key: 'patient_id', label: 'Patient', type: 'patient_select', required: true },
        { key: 'report_type', label: 'Report Type', type: 'select', options: ['Monthly Summary', 'Weekly Summary', 'Critical Review', 'Cardiac Report', 'Pulmonary Report', 'Neurology Report', 'Diabetes Report', 'Oncology Report', 'Weight Management', 'Respiratory Report', 'Prenatal Report', 'Rheumatology Report', 'INR Report'] },
        { key: 'title', label: 'Title', required: true },
        { key: 'content', label: 'Content', type: 'textarea' },
        { key: 'generated_by', label: 'Generated By' },
        { key: 'date_range_start', label: 'Date Range Start', type: 'date' },
        { key: 'date_range_end', label: 'Date Range End', type: 'date' },
        { key: 'status', label: 'Status', type: 'select', options: ['completed', 'draft', 'pending'] },
      ]}
    />
  );
}
